project:
  type: website
  output-dir: docs

website:
  title: "Jihyeon Bae"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
      - href: software.qmd
        text: Software


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



