---
title: "Teaching"
---

## University of Washington

**Instructor of Record**
- Politics and Law of International Human Rights — Summer 2025  

**Teaching Assistant**
- Supreme Court and American Political Development - Winter 2026
- International Conflict — Winter 2024  
- Politics of International Law — Winter 2023  
- Comparative Law and Courts — Autumn 2023; Winter 2020, 2022 (x2)  
- War and Strategy — Winter 2022  
- International Organizations — Winter 2021  
- Introduction to International Relations (First-Year Only) — Autumn 2021  

## Kyung Hee University

**Instructor of Record**
- East Asia International Relations — Winter 2019  
- Introduction to Economics I — Spring 2019  
- Global Data Analysis for Economics and Business (Lab Instructor) — Spring 2018  

**Instructor (in Korean, with partner universities)**
- Advanced Reading (with Tang Long University, Vietnam) — Winter 2020  
- Comparative Area Studies (with Higher School of Economics, Moscow) — Spring 2019  
- East Asian International Relations (with Higher School of Economics, Moscow) — Fall 2019  
