project:
  type: website
  output-dir: docs

website:
  title: "Jihyeon Bae"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
    right: 
      - href: mailto:jihyeonb@uw.edu
        icon: envelope
      - href: https://github.com/Jihyeonbae
        icon: github


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



